"""验证 PostgreSQL 版本、主键生成策略及 SQL 局部改写边界。"""

import argparse
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch


sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("convert_sql_versions", ROOT / "scripts/convert_sql.py")
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)
SOURCE = ("CREATE TABLE `t` (\n  `id` bigint NOT NULL,\n  `label` varchar(100),\n"
          "  PRIMARY KEY (`id`)\n);\n"
          "INSERT INTO `t` VALUES (20, 'int8 bool CREATE SEQUENCE t_seq START 99;');\n"
          "INSERT INTO `t` VALUES (2, '保留内容');\n")
OUTPUT = ("CREATE TABLE dual (id int2);\nINSERT INTO dual VALUES (1);\n"
          "DROP TABLE IF EXISTS t;\nCREATE TABLE t (\n  id int8 NOT NULL,\n  label varchar(100)\n);\n"
          "ALTER TABLE t ADD CONSTRAINT pk_t PRIMARY KEY (id);\n"
          "COMMENT ON COLUMN t.label IS 'int8 bool';\n"
          "INSERT INTO t VALUES (20, 'int8 bool CREATE SEQUENCE t_seq START 99;');\n"
          "INSERT INTO t VALUES (2, '保留内容');\n"
          "DROP SEQUENCE IF EXISTS t_seq;\nCREATE SEQUENCE t_seq START 3;\n")


class PostgresVersionTests(unittest.TestCase):
    def adapt(self, source=SOURCE, output=OUTPUT, version="16", strategy="identity"):
        """通过原始清单校验后执行适配，与实际转换入口保持相同步骤。"""
        tables, _, _ = MODULE.source_inventory(source, "postgres")
        checked, adjustments = MODULE.validate_output(output, tables, "postgres")
        sql, report = MODULE.adapt_postgres(checked, tables, version, strategy)
        return sql, report, adjustments

    def test_released_versions_normalize_to_major(self):
        """接受覆盖范围内的主版本及补丁号，并正确保留 9.x 主版本。"""
        cases = {"9.4": "9.4", "9.4.26": "9.4", "9.5.25": "9.5", "9.6.24": "9.6",
                 "16.15": "16", " 16 ": "16", **{str(v): str(v) for v in range(10, 19)}}
        for version, expected in cases.items():
            with self.subTest(version=version):
                self.assertEqual(MODULE.postgres_version(version), expected)

    def test_invalid_or_unsupported_versions_are_rejected(self):
        """拒绝未覆盖版本、预览字符串及不属于该年代的版本号结构。"""
        for version in (None, "", "9", "9.3", "9.7", "8.4.22", "19", "16beta1", "16-rc1",
                        "latest", "pg16", "016", "16.01", "16.1.2", "9.6.24.1", "16;DROP TABLE t"):
            with self.subTest(version=version), self.assertRaises(ValueError):
                MODULE.postgres_version(version)

    def test_native_postgres_requires_version_and_selects_strategy(self):
        """原生 PostgreSQL 必须明确版本，自动策略以 10 为 identity 边界。"""
        with self.assertRaisesRegex(ValueError, "requires --target-version"):
            MODULE.postgres_options(argparse.Namespace(target="postgres"))
        for version in ("9.4", "9.5", "9.6", "10", "16", "18"):
            args = argparse.Namespace(target="postgres", target_version=version)
            expected = "sequence" if version.startswith("9.") else "identity"
            self.assertEqual(MODULE.postgres_options(args), (version, expected))
        with self.assertRaisesRegex(ValueError, "requires PostgreSQL 10"):
            MODULE.postgres_options(argparse.Namespace(target="postgres", target_version="9.6", pg_id_strategy="identity"))
        self.assertEqual(MODULE.postgres_options(argparse.Namespace(
            target="postgres", target_version="16", pg_id_strategy="sequence")), ("16", "sequence"))

    def test_postgres_options_are_rejected_for_other_dialects(self):
        """派生库与其它方言不会继承 PostgreSQL 版本和 identity 假设。"""
        for target in set(MODULE.TARGETS) - {"postgres"}:
            with self.subTest(target=target):
                self.assertEqual(MODULE.postgres_options(argparse.Namespace(target=target)), (None, None))
                for options in ({"target_version": "16"}, {"pg_id_strategy": "auto"}, {"pg_id_strategy": "sequence"}):
                    with self.assertRaisesRegex(ValueError, "only supported for native postgres"):
                        MODULE.postgres_options(argparse.Namespace(target=target, **options))

    def test_identity_uses_named_sequence_and_max_seed_plus_one(self):
        """现代版本使用允许显式种子 ID 的 identity，保留芋道序列名称和正确起点。"""
        for version in map(str, range(10, 19)):
            with self.subTest(version=version):
                sql, report, adjustments = self.adapt(version=version)
                self.assertIn(f"-- 目标 PostgreSQL 主版本：{version}", sql)
                self.assertIn("-- 主键生成策略：identity", sql)
                self.assertIn("id bigint NOT NULL", sql)
                self.assertIn("DROP SEQUENCE IF EXISTS t_seq;", sql)
                self.assertIn("ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME t_seq START WITH 21);", sql)
                self.assertNotIn("GENERATED ALWAYS", sql)
                self.assertNotIn("\nCREATE SEQUENCE t_seq", sql)
                self.assertEqual(report["id_bindings"], [{"table": "t", "column": "id", "type": "bigint",
                                                        "sequence": "t_seq", "start": 21, "strategy": "identity"}])
                self.assertEqual(adjustments, [{"table": "t", "from": 3, "to": 21}])

    def test_legacy_and_explicit_sequence_bind_default_and_ownership(self):
        """9.x 及显式兼容策略为独立序列补全列默认值与所有权。"""
        for version in ("9.4", "9.5", "9.6", "16"):
            with self.subTest(version=version):
                sql, report, _ = self.adapt(version=version, strategy="sequence")
                self.assertIn("CREATE SEQUENCE t_seq START 21;", sql)
                self.assertIn("ALTER SEQUENCE t_seq OWNED BY t.id;", sql)
                self.assertIn("ALTER TABLE t ALTER COLUMN id SET DEFAULT nextval('t_seq'::regclass);", sql)
                self.assertNotIn("AS IDENTITY", sql)
                self.assertEqual(report["id_strategy"], "sequence")

    def test_type_changes_do_not_touch_names_comments_or_seed_strings(self):
        """仅规范化建表列类型，保留与类型同名的列、注释、默认值和数据原文。"""
        source = SOURCE.replace("`label` varchar(100)", "`label` varchar(100),\n  `int8` int,\n  `bool` bit")
        source = source.replace("');\n", "', 1, b'0');\n")
        output = OUTPUT.replace("label varchar(100)", "label varchar(100) DEFAULT 'int8',\n  int8 int4,\n  bool bool")
        output = output.replace("');\n", "', 1, '0');\n").replace("IS 'int8 bool', 1, '0');", "IS 'int8 bool';")
        sql, report, _ = self.adapt(source=source, output=output)
        self.assertIn("int8 integer", sql)
        self.assertIn("bool boolean", sql)
        self.assertIn("label varchar(100) DEFAULT 'int8'", sql)
        self.assertIn("COMMENT ON COLUMN t.label IS 'int8 bool';", sql)
        self.assertIn("'int8 bool CREATE SEQUENCE t_seq START 99;'", sql)
        self.assertEqual({item["to"] for item in report["type_changes"]}, {"smallint", "integer", "bigint", "boolean"})

    def test_id_requires_scalar_integer_without_preexisting_default(self):
        """对非整数、数组及已有默认值明确失败，不覆盖现有主键生成规则。"""
        cases = [OUTPUT.replace("id int8 NOT NULL", "id varchar(30) NOT NULL"),
                 OUTPUT.replace("id int8 NOT NULL", "id int8[] NOT NULL"),
                 OUTPUT.replace("id int8 NOT NULL", "id int8 NOT NULL DEFAULT 7"),
                 OUTPUT.replace("id int8 NOT NULL", "id int8 GENERATED BY DEFAULT AS IDENTITY")]
        for output in cases:
            with self.subTest(output=output), self.assertRaises(ValueError):
                self.adapt(output=output)
        with self.assertRaisesRegex(ValueError, "already has a default"):
            self.adapt(source=SOURCE.replace("bigint NOT NULL", "bigint NOT NULL DEFAULT 7"))

    def test_id_range_rejects_seed_overflow_and_exhausted_next_value(self):
        """各整数宽度都校验种子下界与下一个自增值上界。"""
        for token, bits in (("int2", 16), ("int4", 32), ("int8", 64)):
            output = OUTPUT.replace("id int8", "id " + token)
            for seed in (1 << (bits - 1), (1 << (bits - 1)) - 1, -(1 << (bits - 1)) - 1):
                with self.subTest(token=token, seed=seed), self.assertRaisesRegex(ValueError, "range"):
                    self.adapt(source=SOURCE.replace("(20,", f"({seed},"),
                               output=output.replace("(20,", f"({seed},"))

    def test_negative_ids_keep_a_positive_sequence_start(self):
        """只有负数种子时自增起点仍为 1，同时保留合法最小主键。"""
        source = SOURCE.replace("(20,", "(-9223372036854775808,").replace("(2,", "(-2,")
        output = OUTPUT.replace("(20,", "(-9223372036854775808,").replace("(2,", "(-2,")
        sql, report, _ = self.adapt(source=source, output=output)
        self.assertIn("START WITH 1", sql)
        self.assertEqual(report["id_bindings"][0]["start"], 1)

    def test_tables_without_id_are_not_bound(self):
        """无 id 的业务表及辅助 dual 表不生成 identity 或列默认值绑定。"""
        source = "CREATE TABLE `lookup` (\n  `name` varchar(100)\n);\nINSERT INTO `lookup` VALUES ('int8');\n"
        output = ("CREATE TABLE dual (id int2);\nINSERT INTO dual VALUES (1);\n"
                  "CREATE TABLE lookup (name varchar(100));\nINSERT INTO lookup VALUES ('int8');\n"
                  "CREATE SEQUENCE lookup_seq START 1;\n")
        sql, report, _ = self.adapt(source=source, output=output)
        self.assertNotIn("ALTER TABLE", sql)
        self.assertEqual(report["id_bindings"], [])
        self.assertIn("CREATE TABLE dual (id smallint)", sql)

    def test_report_and_default_filename_capture_selected_version(self):
        """实际包装器生成带版本文件名与报告，源 SQL 和转换器保持原样。"""
        with tempfile.TemporaryDirectory() as directory:
            project = Path(directory)
            (project / "sql/tools").mkdir(parents=True)
            (project / "sql/mysql").mkdir()
            source = project / "sql/mysql/ruoyi-vue-pro.sql"
            source.write_text(SOURCE, encoding="utf-8")
            converter = project / "sql/tools/convertor.py"
            converter.write_text("# mock converter\n", encoding="utf-8")
            original = source.read_bytes(), converter.read_bytes()
            for requested in ("9.6.24", "16.15"):
                args = argparse.Namespace(project_root=project, target="postgres", target_version=requested,
                                          pg_id_strategy=None, source=None, output=None, timeout=30)
                process = subprocess.CompletedProcess([], 0, OUTPUT.encode("utf-8"), b"")
                with patch.object(MODULE.importlib.metadata, "version", return_value="test"), \
                        patch.object(MODULE.subprocess, "run", return_value=process):
                    report, path = MODULE.convert(args)
                version = "9.6" if requested.startswith("9.") else "16"
                self.assertEqual(report["status"], "generated_only")
                self.assertEqual(report["requested_target_version"], requested)
                self.assertEqual(report["target_version"], version)
                self.assertEqual(report["postgres_id_strategy"], "sequence" if version == "9.6" else "identity")
                self.assertEqual(report["database_validation"], "not_run")
                self.assertEqual(report["output_file"], f"ruoyi-vue-pro.postgres{version}.sql")
                self.assertEqual(json.loads(path.read_text(encoding="utf-8"))["postgres_adaptations"], report["postgres_adaptations"])
                self.assertTrue((path.parent / report["output_file"]).is_file())
            self.assertEqual((source.read_bytes(), converter.read_bytes()), original)

    def test_failed_adaptation_does_not_publish_output(self):
        """主键适配失败只产生失败报告，不交付部分 SQL。"""
        with tempfile.TemporaryDirectory() as directory:
            project = Path(directory)
            (project / "sql/tools").mkdir(parents=True)
            (project / "sql/tools/convertor.py").write_text("# mock converter\n", encoding="utf-8")
            source = project / "input.sql"
            source.write_text(SOURCE, encoding="utf-8")
            args = argparse.Namespace(project_root=project, target="postgres", target_version="16",
                                      source=source, output=None, timeout=30)
            process = subprocess.CompletedProcess([], 0, OUTPUT.replace("id int8", "id text").encode("utf-8"), b"")
            with patch.object(MODULE.importlib.metadata, "version", return_value="test"), \
                    patch.object(MODULE.subprocess, "run", return_value=process):
                report, path = MODULE.convert(args)
            self.assertEqual(report["status"], "failed")
            self.assertEqual(report["database_validation"], "not_run")
            self.assertTrue(path.is_file())
            self.assertFalse((path.parent / "input.postgres16.sql").exists())

    def test_cli_version_alias_and_missing_version(self):
        """命令行接受 pg-version 别名，缺少版本时在调用项目转换器前失败。"""
        command = [sys.executable, "-X", "utf8", str(ROOT / "scripts/convert_sql.py"),
                   "--project-root", str(ROOT), "--target", "pg"]
        missing = subprocess.run(command, capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(missing.returncode, 1)
        self.assertIn("requires --target-version", json.loads(missing.stdout)["errors"][0])
        alias = subprocess.run(command + ["--pg-version", "16.15"], capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(alias.returncode, 1)
        self.assertIn("Project must contain", json.loads(alias.stdout)["errors"][0])


if __name__ == "__main__":
    unittest.main()
