"""Generate and structurally check SQL with a project's sql/tools/convertor.py."""

import argparse
from collections import Counter
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import re
import subprocess
import sys


TARGETS = ("postgres", "oracle", "sqlserver", "dm8", "kingbase", "opengauss", "highgo")
ALIASES = {
    "postgresql": "postgres", "pg": "postgres", "甲骨文": "oracle",
    "mssql": "sqlserver", "sql server": "sqlserver", "sql-server": "sqlserver",
    "dm": "dm8", "达梦": "dm8", "达梦8": "dm8", "人大金仓": "kingbase",
    "金仓": "kingbase", "kingbasees": "kingbase", "open gauss": "opengauss",
    "华为opengauss": "opengauss", "瀚高": "highgo",
}
POSTGRES_TARGETS = {"postgres", "kingbase", "opengauss", "highgo"}
SEQUENCE_TARGETS = POSTGRES_TARGETS | {"oracle"}
DUAL_TARGETS = POSTGRES_TARGETS | {"sqlserver"}
KNOWN_CONVERTER = "985cbc60c37b5aa72955f51bfdc685782e9960a18f87a644597e155d7f7dd978"
CREATE = re.compile(r"\bCREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?([A-Za-z_][A-Za-z0-9_]*)`?\s*\(", re.I)
INSERT = re.compile(r"\bINSERT\s+INTO\s+`?([A-Za-z_][A-Za-z0-9_]*)`?", re.I)
POSTGRES_TYPE_NAMES = {"int2": "smallint", "int4": "integer", "int8": "bigint", "bool": "boolean"}
POSTGRES_INTEGER_BITS = {"smallint": 16, "integer": 32, "int": 32, "bigint": 64}


def postgres_version(value):
    """将正式 PostgreSQL 版本归一到主版本，拒绝未覆盖的版本与预览版本。"""
    version = str(value).strip()
    if not re.fullmatch(r"[1-9]\d*(?:\.(?:0|[1-9]\d*)){0,2}", version):
        raise ValueError("PostgreSQL version must be a released numeric version, such as 16 or 16.15")
    parts = [int(part) for part in version.split(".")]
    if parts[0] == 9 and len(parts) >= 2 and parts[1] in {4, 5, 6}:
        return f"9.{parts[1]}"
    if 10 <= parts[0] <= 18 and len(parts) <= 2:
        return str(parts[0])
    raise ValueError("Supported PostgreSQL versions are 9.4, 9.5, 9.6 and 10 through 18")


def postgres_options(args):
    """核对原生 PostgreSQL 的必填版本与主键策略，防止误用于派生数据库。"""
    requested_version = getattr(args, "target_version", None)
    requested_strategy = getattr(args, "pg_id_strategy", None)
    if args.target != "postgres":
        if requested_version is not None or requested_strategy is not None:
            raise ValueError("--target-version / --pg-version and --pg-id-strategy are only supported for native postgres")
        return None, None
    if requested_version is None:
        raise ValueError("Native PostgreSQL conversion requires --target-version (or --pg-version), for example 16")
    version = postgres_version(requested_version)
    strategy = requested_strategy or "auto"
    if strategy not in {"auto", "identity", "sequence"}:
        raise ValueError("PostgreSQL id strategy must be auto, identity or sequence")
    if strategy == "auto":
        strategy = "sequence" if version.startswith("9.") else "identity"
    if strategy == "identity" and version.startswith("9."):
        raise ValueError("GENERATED BY DEFAULT AS IDENTITY requires PostgreSQL 10 or later")
    return version, strategy


def apply_sql_edits(sql, edits):
    """按已扫描位置从后向前替换 SQL，保持注释、标识符及种子数据的原文。"""
    for start, end, replacement in sorted(edits, reverse=True):
        sql = sql[:start] + replacement + sql[end:]
    return sql


def target_name(value):
    value = value.strip().casefold()
    return ALIASES.get(value, value)


def mask_sql(text, backslash_escapes=True):
    """Blank strings/comments while preserving identifiers, offsets and newlines."""
    masked = list(text)
    literals = []
    index = 0
    while index < len(text):
        start = index
        if text.startswith("/*", index):
            end = text.find("*/", index + 2)
            if end < 0:
                raise ValueError("Unterminated SQL comment")
            index = end + 2
        elif text[index] == "#" or (text.startswith("--", index)
                                    and (index + 2 == len(text) or text[index + 2].isspace())):
            end = text.find("\n", index)
            index = len(text) if end < 0 else end
        elif text[index] in "'\"":
            quote = text[index]
            index += 1
            while index < len(text):
                if text[index] == "\\" and backslash_escapes:
                    index += 2
                elif text[index] == quote:
                    if index + 1 < len(text) and text[index + 1] == quote:
                        index += 2
                    else:
                        index += 1
                        break
                else:
                    index += 1
            else:
                raise ValueError("Unterminated SQL string")
            literals.append((start, text[start:index]))
        elif text[index] == "`":
            end = text.find("`", index + 1)
            if end < 0:
                raise ValueError("Unterminated quoted identifier")
            index = end + 1
            continue
        else:
            index += 1
            continue
        masked[start:index] = ["\n" if char == "\n" else " " for char in text[start:index]]
    return "".join(masked), literals


def source_inventory(text, target):
    """检查转换器支持的源语句，并收集表、种子主键范围与默认值信息。"""
    _, original_literals = mask_sql(text)
    if any("\n" in literal or literal.startswith('"') for _, literal in original_literals):
        raise ValueError("Multiline or double-quoted SQL strings need explicit normalization before conversion")
    # This is the single wrapped INSERT line form the upstream loader supports.
    text = text.replace(")\nVALUES ", ") VALUES ")
    masked, literals = mask_sql(text)
    errors = []
    ignored = 0
    for statement in masked.split(";"):
        statement = statement.strip()
        if not statement:
            continue
        if not re.match(r"(?:CREATE\s+TABLE|INSERT\s+INTO|DROP\s+TABLE|SET|USE|BEGIN|COMMIT)\b", statement, re.I):
            errors.append("Unsupported statement; only table DDL, standard INSERT and dump session statements are accepted")
        elif re.match(r"(?:DROP|SET|USE|BEGIN|COMMIT)\b", statement, re.I):
            ignored += 1
    if re.search(r"\b(?:FOREIGN\s+KEY|REFERENCES|GENERATED\s+ALWAYS|PARTITION\s+BY|FULLTEXT|SPATIAL)\b|\bCHECK\s*\(", masked, re.I):
        errors.append("Foreign keys, CHECK, generated columns, partitions and special indexes need a separate conversion")
    for comment in re.finditer(r"/\*!([\s\S]*?)\*/", text):
        inside_literal = any(offset <= comment.start() < offset + len(literal) for offset, literal in literals)
        if not inside_literal and re.search(r"\b(?:CREATE|ALTER|INSERT|UPDATE|DELETE)\b", comment.group(1), re.I):
            errors.append("Executable MySQL comments contain objects/data not handled by this converter")
    for offset, literal in literals:
        if re.search(r"ENGINE| CHARACTER SET \w+| COLLATE \w+|UNIQUE INDEX| KEY `|`[^`]+`\(\d+\)|USING\s+BTREE\s+COMMENT", literal):
            errors.append("A string/comment intersects upstream global cleanup rules; normalize a reviewed copy first")
        if re.search(r"\bCOMMENT\s*(?:=\s*)?$", text[max(0, offset - 32):offset], re.I):
            if "\\'" in literal or "''" in literal[1:-1]:
                errors.append("Escaped quotes in comments need explicit target-dialect handling")
    tables = {}
    skipped = []
    creates = list(CREATE.finditer(masked))
    if len(creates) != len(re.findall(r"\bCREATE\s+TABLE\b", masked, re.I)):
        errors.append("A CREATE TABLE name/form is unsupported; use simple unqualified ASCII identifiers")
    for match in creates:
        name = match.group(1).lower()
        end = masked.find(";", match.end())
        if end < 0:
            errors.append(f"Missing CREATE TABLE terminator: {name}")
            continue
        if name.startswith("qrtz"):
            skipped.append(name)
            continue
        if name in tables:
            errors.append(f"Duplicate CREATE TABLE: {name}")
        if not text[match.start():].startswith("CREATE TABLE "):
            errors.append(f"Use the converter's uppercase CREATE TABLE format: {name}")
        body = masked[match.end():end]
        parts = []
        depth, start = 0, 0
        for position, character in enumerate(body):
            if character == "(":
                depth += 1
            elif character == ")":
                depth -= 1
                if depth < 0:
                    parts.append(body[start:position])
                    break
            elif character == "," and depth == 0:
                parts.append(body[start:position])
                start = position + 1
        columns = []
        id_has_default = False
        for part in parts:
            column = re.match(r"\s*`([A-Za-z_][A-Za-z0-9_]*)`\s+([\s\S]+)", part)
            if column:
                columns.append(column.group(1).lower())
                if column.group(1).lower() == "id":
                    id_has_default = bool(re.search(r"\bDEFAULT\b", column.group(2), re.I))
                if re.search(r"\b(?:UNIQUE|PRIMARY\s+KEY)\b", column.group(2), re.I):
                    errors.append(f"Inline column constraints need explicit table-level definitions: {name}")
                if re.search(r"\bAS\s*\(|\b(?:VIRTUAL|STORED)\b", column.group(2), re.I):
                    errors.append(f"Generated columns need a separate conversion: {name}")
            elif not re.match(r"\s*(?:PRIMARY\s+KEY|UNIQUE|KEY|INDEX|CONSTRAINT)\b", part, re.I):
                errors.append(f"Unsupported column/table definition: {name}")
        if not columns:
            errors.append(f"Backtick-quoted column definitions are required: {name}")
        primary = re.search(r"\bPRIMARY\s+KEY\s*\(([^)]*)\)", body, re.I)
        keys = [key.strip().strip('`').lower() for key in primary.group(1).split(',')] if primary else []
        if ("id" in columns and keys != ["id"]) or ("id" not in columns and keys):
            errors.append(f"Primary key is outside the converter's id-only convention: {name}")
        tables[name] = {"columns": columns, "max_id": 0, "min_id": 0,
                        "id_has_default": id_has_default, "inserts": 0}
    if not tables:
        errors.append("No supported business CREATE TABLE statements found")
    if "dual" in tables and target in DUAL_TARGETS:
        errors.append("Source dual conflicts with the converter's automatically generated dual table")
    for match in INSERT.finditer(masked):
        name = match.group(1).lower()
        if name in skipped:
            continue
        start = masked.rfind("\n", 0, match.start()) + 1
        end = masked.find("\n", match.start())
        end = len(text) if end < 0 else end
        line, masked_line = text[start:end], masked[start:end]
        row = re.fullmatch(r"INSERT INTO `([^`]+)`(?:\s*\(([^)]*)\))? VALUES \((.*)\);\s*", line)
        if not row or masked_line.count(";") != 1 or re.search(r"\)\s*,\s*\(", masked_line):
            errors.append(f"INSERT must be one complete uppercase, unindented, single-row statement per line: {name}")
            continue
        values = masked_line[row.start(3):row.end(3)]
        boundaries = [-1] + [index for index, character in enumerate(values) if character == ","] + [len(values)]
        tokens = [row.group(3)[left + 1:right].strip() for left, right in zip(boundaries, boundaries[1:])]
        literal = re.compile(r"(?:NULL|[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?|b'[01]'|'(?:[^'\\]|\\.|'')*')", re.S)
        if any(not literal.fullmatch(token) for token in tokens):
            errors.append(f"INSERT values must be literal data; functions, expressions and trailing clauses need a separate conversion: {name}")
            continue
        if name not in tables:
            errors.append(f"INSERT references a table without converted DDL: {name}")
            continue
        table = tables[name]
        table["inserts"] += 1
        columns = ([column.strip().strip('`').lower() for column in row.group(2).split(',')]
                   if row.group(2) else table["columns"])
        if len(tokens) != len(columns) or any(column not in table["columns"] for column in columns):
            errors.append(f"INSERT column/value count or column names differ from the table: {name}")
        if "id" in table["columns"]:
            number = re.match(r"\s*(-?\d+)\s*(?:,|$)", row.group(3))
            if not columns or columns[0] != "id" or not number:
                errors.append(f"Seed rows require a numeric id in the first value position: {name}")
            else:
                seed_id = int(number.group(1))
                table["max_id"] = max(table["max_id"], seed_id)
                table["min_id"] = min(table["min_id"], seed_id)
        elif target in {"sqlserver", "dm8"}:
            errors.append(f"Seed rows on a table without id would emit invalid IDENTITY_INSERT: {name}")
    if errors:
        raise ValueError("; ".join(dict.fromkeys(errors)))
    return tables, skipped, ignored


def validate_output(sql, tables, target):
    """核对输出对象和 INSERT 清单，并将序列起点修正为有效主键最大值加一。"""
    masked, _ = mask_sql(sql, backslash_escapes=target not in POSTGRES_TARGETS)
    expected_tables = Counter({name: 1 for name in tables})
    expected_inserts = Counter({name: data["inserts"] for name, data in tables.items() if data["inserts"]})
    if target in DUAL_TARGETS:
        expected_tables["dual"] += 1
        expected_inserts["dual"] += 1
    if Counter(m.group(1).lower() for m in CREATE.finditer(masked)) != expected_tables:
        raise ValueError("Generated table inventory differs from source (excluding Quartz and accounting for dual)")
    if Counter(m.group(1).lower() for m in INSERT.finditer(masked)) != expected_inserts:
        raise ValueError("Generated INSERT inventory differs from source")
    if re.search(r"\bNone\b", masked):
        raise ValueError("Converter emitted an unsupported type/precision placeholder: None")
    adjustments = []
    edits = []
    if target in SEQUENCE_TARGETS:
        for name, data in tables.items():
            if "id" not in data["columns"]:
                continue
            pattern = re.compile(rf"^([ \t]*CREATE SEQUENCE {re.escape(name)}_seq\s+START(?: WITH)?\s+)(\d+)", re.I | re.M)
            matches = list(pattern.finditer(masked))
            if len(matches) != 1:
                raise ValueError(f"Expected one sequence for table: {name}")
            old = int(matches[0].group(2))
            start = data["max_id"] + 1
            if old != start:
                edits.append((matches[0].start(2), matches[0].end(2), str(start)))
                adjustments.append({"table": name, "from": old, "to": start})
    return apply_sql_edits(sql, edits), adjustments


def postgres_columns(sql):
    """扫描已生成 CREATE TABLE 的列定义，仅返回明确可定位的列类型和约束。"""
    masked, _ = mask_sql(sql, backslash_escapes=False)
    tables = {}
    for table in CREATE.finditer(masked):
        name = table.group(1).lower()
        depth, start = 0, table.end()
        parts = []
        for position in range(start, len(masked)):
            character = masked[position]
            if character == "(":
                depth += 1
            elif character == ")":
                if depth == 0:
                    parts.append((start, position))
                    break
                depth -= 1
            elif character == "," and depth == 0:
                parts.append((start, position))
                start = position + 1
            elif character == ";" and depth == 0:
                raise ValueError(f"Unterminated generated CREATE TABLE: {name}")
        else:
            raise ValueError(f"Unterminated generated CREATE TABLE: {name}")
        columns = {}
        for start, end in parts:
            part = sql[start:end]
            if re.match(r"\s*(?:PRIMARY\s+KEY|UNIQUE|CONSTRAINT|CHECK|FOREIGN\s+KEY)\b", part, re.I):
                continue
            column = re.match(r'\s*([A-Za-z_][A-Za-z0-9_]*|"[A-Za-z_][A-Za-z0-9_]*"|`[A-Za-z_][A-Za-z0-9_]*`)\s+([A-Za-z_][A-Za-z0-9_]*)\b', part)
            if not column:
                raise ValueError(f"Unsupported generated column definition: {name}")
            column_name = column.group(1).strip('"`').lower()
            if column_name in columns:
                raise ValueError(f"Duplicate generated column: {name}.{column_name}")
            columns[column_name] = {
                "type": column.group(2).lower(),
                "type_start": start + column.start(2), "type_end": start + column.end(2),
                "constraints": masked[start + column.end(2):end],
            }
        tables[name] = columns
    return masked, tables


def adapt_postgres(sql, tables, version, strategy):
    """按目标版本规范化列类型并绑定 id 序列，保留芋道约定的序列名称。"""
    masked, generated_tables = postgres_columns(sql)
    edits, type_changes, bindings = [], [], []
    for name, columns in generated_tables.items():
        for column_name, column in columns.items():
            original_type = column["type"]
            if original_type in POSTGRES_TYPE_NAMES:
                column["type"] = POSTGRES_TYPE_NAMES[original_type]
                edits.append((column["type_start"], column["type_end"], column["type"]))
                type_changes.append({"table": name, "column": column_name,
                                     "from": original_type, "to": column["type"]})
    for name, data in tables.items():
        if "id" not in data["columns"]:
            continue
        column = generated_tables.get(name, {}).get("id")
        if column is None or column["type"] not in POSTGRES_INTEGER_BITS:
            raise ValueError(f"PostgreSQL id binding requires a smallint, integer or bigint column: {name}.id")
        if data.get("id_has_default") or re.search(r"\b(?:DEFAULT|GENERATED)\b", column["constraints"], re.I):
            raise ValueError(f"PostgreSQL id already has a default or generation expression; explicit review required: {name}.id")
        if column["constraints"].lstrip().startswith(("[", "(")):
            raise ValueError(f"PostgreSQL id binding requires a scalar integer type: {name}.id")
        bits = POSTGRES_INTEGER_BITS[column["type"]]
        minimum, maximum = -(1 << (bits - 1)), (1 << (bits - 1)) - 1
        start = data["max_id"] + 1
        if data.get("min_id", 0) < minimum or start > maximum:
            raise ValueError(f"PostgreSQL id values or next sequence value exceed {column['type']} range: {name}.id")
        sequence = name + "_seq"
        if len(sequence.encode("utf-8")) > 63:
            raise ValueError(f"PostgreSQL sequence name exceeds 63 bytes: {sequence}")
        pattern = re.compile(rf"\bCREATE\s+SEQUENCE\s+{re.escape(sequence)}\s+START(?:\s+WITH)?\s+(\d+)\s*;", re.I)
        matches = list(pattern.finditer(masked))
        if len(matches) != 1 or int(matches[0].group(1)) != start:
            raise ValueError(f"Unexpected PostgreSQL sequence definition after validation: {sequence}")
        match = matches[0]
        if strategy == "identity":
            replacement = (f"ALTER TABLE {name} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY "
                           f"(SEQUENCE NAME {sequence} START WITH {start});")
        else:
            replacement = (sql[match.start():match.end()] + "\n"
                           f"ALTER SEQUENCE {sequence} OWNED BY {name}.id;\n"
                           f"ALTER TABLE {name} ALTER COLUMN id SET DEFAULT nextval('{sequence}'::regclass);")
        edits.append((match.start(), match.end(), replacement))
        bindings.append({"table": name, "column": "id", "type": column["type"],
                         "sequence": sequence, "start": start, "strategy": strategy})
    header = (f"-- 目标 PostgreSQL 主版本：{version}\n"
              f"-- 主键生成策略：{strategy}\n"
              "-- 仅生成 SQL；尚未在目标数据库执行验证。\n\n")
    return header + apply_sql_edits(sql, edits), {
        "target_version": version, "id_strategy": strategy,
        "type_changes": type_changes, "id_bindings": bindings,
    }


def convert(args):
    """执行只读源文件转换并生成新 SQL 与报告，原生 PostgreSQL 必须明确版本。"""
    version, strategy = postgres_options(args)
    project = args.project_root.resolve()
    source = (project / (args.source or "sql/mysql/ruoyi-vue-pro.sql")).resolve()
    converter = project / "sql/tools/convertor.py"
    target_suffix = f"postgres{version}" if version else args.target
    output = (project / (args.output or f"sql/converted/{source.stem}.{target_suffix}.sql")).resolve()
    report_path = output.with_suffix(output.suffix + ".report.json")
    diagnostic_path = output.with_suffix(output.suffix + ".stderr.log")
    if not source.is_file() or not converter.is_file():
        raise ValueError("Project must contain the input SQL and sql/tools/convertor.py")
    if output in {source, converter.resolve()} or any(path.exists() or path.is_symlink() for path in (output, report_path, diagnostic_path)):
        raise ValueError("Choose a new output path; source, converter and existing artifacts cannot be overwritten")
    source_bytes = source.read_bytes()
    report = {
        "status": "failed", "target": args.target, "source_name": source.name,
        "source_sha256": hashlib.sha256(source_bytes).hexdigest(),
        "converter_sha256": hashlib.sha256(converter.read_bytes()).hexdigest(),
        "database_validation": "not_run", "errors": [], "warnings": [],
    }
    if version:
        report.update({"requested_target_version": args.target_version, "target_version": version,
                       "postgres_id_strategy": strategy})
    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        tables, skipped, ignored = source_inventory(source_bytes.decode("utf-8-sig"), args.target)
        report.update({"tables": list(tables), "source_insert_statements": sum(t["inserts"] for t in tables.values()),
                       "quartz_tables_skipped": skipped, "source_session_or_drop_statements_ignored": ignored})
        try:
            report["simple_ddl_parser_version"] = importlib.metadata.version("simple-ddl-parser")
        except importlib.metadata.PackageNotFoundError:
            raise ValueError("Missing simple-ddl-parser; run this wrapper in the documented isolated uv environment") from None
        # PLY's first parser build can emit megabytes of INFO grammar logs.
        # Keep warnings/errors and the converter's direct stderr diagnostics.
        bootstrap = "import logging,runpy,sys; logging.disable(logging.INFO); p=sys.argv.pop(1); sys.argv[0]=p; runpy.run_path(p,run_name='__main__')"
        process = subprocess.run(
            [sys.executable, "-X", "utf8", "-c", bootstrap, str(converter), args.target, str(source)],
            cwd=converter.parent, capture_output=True, timeout=args.timeout,
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        )
        report["converter_exit_code"] = process.returncode
        if process.stderr.strip():
            with diagnostic_path.open("xb") as stream:
                stream.write(process.stderr)
            report["diagnostic_file"] = diagnostic_path.name
            raise ValueError("Converter emitted diagnostics; inspect the local stderr log before publishing SQL")
        if process.returncode:
            raise ValueError(f"Converter failed with exit code {process.returncode}")
        sql, adjustments = validate_output(process.stdout.decode("utf-8"), tables, args.target)
        report["sequence_adjustments"] = adjustments
        if version:
            sql, report["postgres_adaptations"] = adapt_postgres(sql, tables, version, strategy)
        report["warnings"].append("generated_only: target database import, type ranges, defaults, comments, indexes and data semantics require validation")
        if skipped:
            report["warnings"].append("Quartz tables are excluded; use the target database's separate Quartz script")
        if report["converter_sha256"] != KNOWN_CONVERTER:
            report["warnings"].append("Project converter differs from the inspected source version; review its changes")
        report["destructive_statements"] = len(re.findall(r"\bDROP\s+(?:TABLE|SEQUENCE)\b", mask_sql(sql, backslash_escapes=args.target not in POSTGRES_TARGETS)[0], re.I))
        encoded = sql.encode("utf-8")
        with output.open("xb") as stream:
            stream.write(encoded)
        report.update({"status": "generated_only", "output_sha256": hashlib.sha256(encoded).hexdigest(), "output_file": output.name})
    except (ValueError, UnicodeError, OSError, subprocess.TimeoutExpired) as error:
        report["errors"].append(str(error))
    with report_path.open("x", encoding="utf-8") as stream:
        json.dump(report, stream, ensure_ascii=False, indent=2)
        stream.write("\n")
    return report, report_path


def main():
    """解析命令参数并以 JSON 输出转换结果或失败原因。"""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--target", type=target_name, choices=TARGETS, required=True)
    parser.add_argument("--target-version", "--pg-version", dest="target_version",
                        help="Required for native PostgreSQL: 9.4, 9.5, 9.6 or 10-18; patch versions are normalized")
    parser.add_argument("--pg-id-strategy", choices=("auto", "identity", "sequence"),
                        help="Native PostgreSQL only: auto uses identity on 10+ and sequence on 9.x")
    parser.add_argument("--source", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--timeout", type=int, default=300)
    args = parser.parse_args()
    try:
        report, path = convert(args)
        print(json.dumps({"status": report["status"], "target": args.target,
                          "report": str(path), "errors": report["errors"]}, ensure_ascii=False))
        return 0 if report["status"] == "generated_only" else 1
    except (ValueError, OSError) as error:
        print(json.dumps({"status": "failed", "errors": [str(error)]}, ensure_ascii=False))
        return 1


if __name__ == "__main__":
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    sys.exit(main())
